const summaryIcons = {
  '01d': 'sun.png',
  '01n': 'bright-moon.png',
  '02d': 'partly-cloudy-day.png',
  '02n': 'partly-cloudy-night.png',
  '03d': 'cloud.png',
  '03n': 'cloud.png',
  '04d': 'clouds.png',
  '04n': 'clouds.png',
  '09d': 'rain.png',
  '09n': 'rain.png',
  '10d': 'heavy-rain.png',
  '10n': 'heavy-rain.png',
  '11d': 'storm.png',
  '11n': 'storm.png',
  '13d': 'sleet.png',
  '13n': 'sleet.png',
  '50d': 'fog.png',
  '50n': 'fog.png',
};

const weatherIcons = {
  '01d': 'clear-day',
  '01n': 'clear-night',
  '02d': 'partly-cloudy-day',
  '02n': 'partly-cloudy-night',
  '03d': 'cloudy',
  '03n': 'cloudy',
  '04d': 'cloudy',
  '04n': 'cloudy',
  '09d': 'rain',
  '09n': 'rain',
  '10d': 'rain',
  '10n': 'rain',
  '11d': 'thunderstorm',
  '11n': 'thunderstorm',
  '13d': 'sleet',
  '13n': 'sleet',
  '50d': 'fog',
  '50n': 'fog',
};

export { weatherIcons, summaryIcons };
